### ISSUE TITLE
Draft the SSB announcement post

### ISSUE THREAD

**Issue by staltz** [scuttlebutt-eu/important-documents#36]

**Comment by arj03** [comment]
I have a draft of this ready. We need to decide on a name first and it would also be nice if the website was ready, but that is not a strict requirement.

If anyone wants to read it, please let me know and I'll pass it along.

**Comment by cblgh** [comment]
i would like to read it :)

**Comment by arj03** [comment]
# European SSB collective officially launched

For the past 9 months, a small group consisting of me, andre, keks,
erick, andre, jacob, alex and zenna (FIXME: linkify) have been trying to get a
foundation for a european network of people interested in working on
SSB started.

It started out with a weekend in the lovely southern Sweden where we
got to knew each other better and made some delicious vegan food
together. After this we have had a string of online meetings working
on out the details on how we want to work together.

FIXME: image and link to SSB post
 - %X2rep8+59E9sPz4Kx7P7bNeoLU0lXvSAsTH9xoBAyJA=.sha256

We wanted to have something ready for the Basel meetup where a lot of
the team members met, but fate would have it otherwise. Then of course
came the whole corona situation. Slow but steady we chucked along and
kept refining what is it we want to do and how we want to do it. It
seems simple, but it actually takes a while especially if you are 7
people, to iron out the kinks.

One of the goals has been to enable us to easier apply for grants in
EU and I'm really happy that the first one went through.

FIXME: link to post once we write that

The consortium is now in a state where we are ready to open it up for
other people. We kept the original team small in order to get
something running and to keep the trust high, which is one of the core
pillars of the organization. I'm really happy and proud of what we
have built, it is a real pleasure to work with this group of people.

If you are interested in knowing more, please get in contact with on
of us :-)

FIXME: link to the github:
 - https://github.com/scuttlebutt-eu/important-documents/blob/master/proposal-membership.md

**Comment by Powersource** [comment]
@arj03 If I understand stuff correctly, the announcement is ready, it's just waiting for a GO?

**Comment by arj03** [comment]
Yes, and maybe the grant post from Zenna.

**Comment by arj03** [comment]
Wup %wBWXSq/+C0/iK7UCfpQH53KGdVngTkqWzebeb6dEi2Q=.sha256
